version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.11
        REQUIREMENTS_FILENAME: requirements.txt
    volumes:
      - ./quack.duckdb:/code/quack.duckdb
      - ./quack.duckdb.wal:/code/quack.duckdb.wal
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./certs/localhost.key:/etc/ssl/private/localhost.key
    depends_on:
      - web
