version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.11
        REQUIREMENTS_FILENAME: requirements.txt
    ports:
      - "80:80"
    volumes:
      - ./quack.duckdb:/code/quack.duckdb
      - ./quack.duckdb.wal:/code/quack.duckdb.wal
